name: Build with SLSA Github Generic Generator
on: 
  push:
  workflow_dispatch:
    inputs:
      thing:
        type: string
        default: "abc123"
        description: "my arbitrary unused input"
permissions:
  contents: read
env:
  ARTIFACT_PATH: "${{ github.workspace }}/app/build/libs/app.jar"
jobs:
  # This step builds our artifacts, uploads them to the workflow run, and
  # outputs their digest.
  build:
    runs-on: ubuntu-latest
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3

    - name: Execute Gradle build
      run: ./gradlew build

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: ${{ env.ARTIFACT_PATH }}

    - name: Generate hashes
      shell: bash
      id: hash
      env:
        ARTIFACT: ${{ env.ARTIFACT_PATH }}
      run: |
        # sha256sum generates sha256 hash for all artifacts.
        # base64 -w0 encodes to base64 and outputs on a single line.
        # sha256sum artifact1 artifact2 ... | base64 -w0
        echo "hashes=$(sha256sum $ARTIFACT | base64 -w0)" >> "$GITHUB_OUTPUT"

  provenance:
    needs: [build]
    permissions:
      actions: read # Needed for detection of GitHub Actions environment.
      id-token: write # Needed for provenance signing and ID
      contents: write # Needed for release uploads
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.0.0
    with:
      base64-subjects: ${{ needs.build.outputs.hashes }}
